name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d82bc154c2a845b7523fd139197b53dd520a9311c90a58465652baa8054751f"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
